name: Deploy Vue frontend to Firebase Hosting

on:
  push:
    branches:
      - main
    paths:
      - "okeem/okeem-front/**"
      - ".github/workflows/firebase-hosting.yml"
  workflow_dispatch: # Pour lancer manuellement

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: okeem/okeem-front

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Firebase Hosting
        run: |
          npm install -g firebase-tools
          firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}
